# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlprojtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mlprojtest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_223e1f91893a4f46aa8f00b5b0b3dbf3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3b7f9c347e7b4851870e056a57bba76b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mlprojtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_223e1f91893a4f46aa8f00b5b0b3dbf3 }}/mlprojtest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlprojtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7639a25505fd4a71bd3d0db5f8cadaa4 }}
        images: 'mlprojtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_223e1f91893a4f46aa8f00b5b0b3dbf3 }}/mlprojtest:${{ github.sha }}'